CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  client VARCHAR(255) NOT NULL,
  type VARCHAR(64) NOT NULL,
  deadline DATE NOT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  paid DECIMAL(10,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  notes TEXT,
  email VARCHAR(190) DEFAULT NULL,
  first_name VARCHAR(100) DEFAULT NULL,
  last_name VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  INDEX(deadline),
  INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS phases (
  id VARCHAR(64) PRIMARY KEY,
  project_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  INDEX(project_id, sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id VARCHAR(64) PRIMARY KEY,
  phase_id VARCHAR(64) NOT NULL,
  label VARCHAR(255) NOT NULL,
  done TINYINT(1) NOT NULL DEFAULT 0,
  est_h DECIMAL(6,2) NOT NULL DEFAULT 0,
  tools VARCHAR(255) NULL,
  sort INT NOT NULL DEFAULT 0,
  deadline DATE NULL,
  FOREIGN KEY (phase_id) REFERENCES phases(id) ON DELETE CASCADE,
  INDEX(phase_id, sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subtasks (
  id VARCHAR(64) PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  label VARCHAR(255) NOT NULL,
  done TINYINT(1) NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 0,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  INDEX(task_id, sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;